name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [backend/auth-service, backend/chat-service, backend/web-sockets-service, frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Check if project changed
        id: changes
        shell: bash
        run: |
          echo "PROJECT_CHANGED=false" >> $GITHUB_ENV

          # Detect commits
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Event: pull_request"
            git fetch origin ${{ github.base_ref }} --depth=1
            BASE=$(git merge-base HEAD origin/${{ github.base_ref }})
          else
            echo "Event: push"
            BASE=$(git rev-parse HEAD^)
          fi

          echo "Comparing changes from $BASE to HEAD"

          # If changes were made, we change to true
          if git diff --name-only $BASE HEAD | grep -q "^${{ matrix.project }}/"; then
            echo "Changes detected in ${{ matrix.project }}"
            echo "PROJECT_CHANGED=true" >> $GITHUB_ENV
          else
            echo "No changes in ${{ matrix.project }}"
          fi

      - name: Install dependencies
        if: env.PROJECT_CHANGED == 'true'
        run: npm install

      - name: Run lint, format, and tests
        if: env.PROJECT_CHANGED == 'true'
        run: |
          echo "ðŸš€ Running Scripts for ${{ matrix.project }}"
          npm --prefix ${{ matrix.project }} run lint
          npm --prefix ${{ matrix.project }} run format
          npm --prefix ${{ matrix.project }} run test
